version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  swagger:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
